//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmprestimoPessoaFisica.ContaCorrenteServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContaCorrente", Namespace="http://schemas.datacontract.org/2004/07/ContaCorrenteServiceService.ContaCorrente" +
        "")]
    [System.SerializableAttribute()]
    public partial class ContaCorrente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdContaCorrenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroAgenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroContaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdContaCorrente {
            get {
                return this.IdContaCorrenteField;
            }
            set {
                if ((this.IdContaCorrenteField.Equals(value) != true)) {
                    this.IdContaCorrenteField = value;
                    this.RaisePropertyChanged("IdContaCorrente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroAgencia {
            get {
                return this.NumeroAgenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroAgenciaField, value) != true)) {
                    this.NumeroAgenciaField = value;
                    this.RaisePropertyChanged("NumeroAgencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroConta {
            get {
                return this.NumeroContaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroContaField, value) != true)) {
                    this.NumeroContaField = value;
                    this.RaisePropertyChanged("NumeroConta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContaCorrenteServiceReference.IContaCorrenteService")]
    public interface IContaCorrenteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContaCorrenteService/Get", ReplyAction="http://tempuri.org/IContaCorrenteService/GetResponse")]
        EmprestimoPessoaFisica.ContaCorrenteServiceReference.ContaCorrente Get(System.Guid IdContaCorrente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContaCorrenteService/Get", ReplyAction="http://tempuri.org/IContaCorrenteService/GetResponse")]
        System.Threading.Tasks.Task<EmprestimoPessoaFisica.ContaCorrenteServiceReference.ContaCorrente> GetAsync(System.Guid IdContaCorrente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContaCorrenteServiceChannel : EmprestimoPessoaFisica.ContaCorrenteServiceReference.IContaCorrenteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContaCorrenteServiceClient : System.ServiceModel.ClientBase<EmprestimoPessoaFisica.ContaCorrenteServiceReference.IContaCorrenteService>, EmprestimoPessoaFisica.ContaCorrenteServiceReference.IContaCorrenteService {
        
        public ContaCorrenteServiceClient() {
        }
        
        public ContaCorrenteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContaCorrenteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContaCorrenteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContaCorrenteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmprestimoPessoaFisica.ContaCorrenteServiceReference.ContaCorrente Get(System.Guid IdContaCorrente) {
            return base.Channel.Get(IdContaCorrente);
        }
        
        public System.Threading.Tasks.Task<EmprestimoPessoaFisica.ContaCorrenteServiceReference.ContaCorrente> GetAsync(System.Guid IdContaCorrente) {
            return base.Channel.GetAsync(IdContaCorrente);
        }
    }
}
